# Generated by Django 2.1.7 on 2020-02-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioFile',
            new_name='Counts',
        ),
    ]
