# Generated by Django 2.1.7 on 2020-02-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200212_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
