# Generated by Django 2.1.7 on 2020-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0003_delete_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillow_used', models.IntegerField(default=0)),
                ('darksky_used', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
