# Generated by Django 2.1.7 on 2020-02-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_counts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counts',
            new_name='Count',
        ),
    ]
