# Generated by Django 2.1.7 on 2020-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200213_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('trade', models.CharField(max_length=200)),
                ('sp_name', models.CharField(max_length=200)),
            ],
        ),
    ]
