# Generated by Django 2.1.7 on 2020-03-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('tax', models.FloatField(default=0, max_length=200)),
                ('surge_protect', models.BooleanField()),
                ('line_protect', models.BooleanField()),
                ('electronics_protect', models.BooleanField()),
                ('discount', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsProtect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LineProtect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SurgeProtect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_cost', models.FloatField()),
                ('maximum_cost', models.FloatField()),
                ('text', models.CharField(default='Coverage', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sys', to='search.Calculator')),
            ],
        ),
        migrations.CreateModel(
            name='WholeHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh', to='search.Calculator')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='calculator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appl', to='search.Calculator'),
        ),
    ]
