# Generated by Django 2.1.7 on 2020-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200313_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='discount',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wholehome',
            name='value',
            field=models.FloatField(),
        ),
    ]
