# Generated by Django 2.2.11 on 2020-04-30 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=10)),
                ('catagory', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('estimated_price', models.FloatField()),
                ('delivery_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('started', 'Started'), ('primarily_delivered', 'Primarily Delivered'), ('completed', 'Completed')], max_length=25)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', "What's app")], max_length=25)),
                ('contact_address', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=10)),
                ('catagory', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('asking_price', models.FloatField(null=True)),
                ('estimated_price', models.FloatField(null=True)),
                ('asking_date', models.DateTimeField(null=True)),
                ('estimated_date', models.DateTimeField(null=True)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', "What's app")], max_length=25)),
                ('contact_address', models.CharField(max_length=100)),
                ('comment', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
