# Generated by Django 2.2.11 on 2020-05-02 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0002_auto_20200502_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='starting_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
