# Generated by Django 2.2.11 on 2020-05-02 18:04

from django.db import migrations, models
from datetime import date    

class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0005_auto_20200502_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='starting_date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
