# Generated by Django 2.2.11 on 2020-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0006_auto_20200502_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
