# Generated by Django 2.2.11 on 2020-05-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0007_estimate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='asking_date',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='estimated_date',
        ),
        migrations.AddField(
            model_name='estimate',
            name='asking_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimated_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='payment_link',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tnxid', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdash.Order')),
            ],
        ),
    ]
