# Generated by Django 2.2.11 on 2020-05-06 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdash', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_percentage',
            field=models.FloatField(default=10),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawn', models.FloatField()),
                ('remaining', models.FloatField()),
                ('method', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
