# Generated by Django 2.2.11 on 2020-05-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0012_auto_20200510_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='catagory',
        ),
    ]
