# Generated by Django 2.2.11 on 2020-05-11 11:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0013_remove_order_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='catagory',
            field=models.CharField(default='kkk', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
