# Generated by Django 2.2.11 on 2020-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0016_samples_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Samples',
            new_name='Sample',
        ),
    ]
